version: '3.1'
services:
  mongodb_container:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: lotterydb
    volumes:
      - ./mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
