export enum ACCOUNT_ROLE {
  ADMIN = 'ADMIN',
  ATC = 'ATC',
  CLIENT = 'CLIENT',
  MANAGE_RESULTS = 'MANAGE_RESULTS',
  TAQUILLA = 'TAQUILLA',
  USER = 'USER',
}

export enum ACCOUNT_STATUS {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED ',
  INACTIVE = 'INACTIVE',
}
